# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lyrics_app_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lyrics_app_ios
  pod 'SpotifyLogin', '~> 0.1'
  pod 'ObjectMapper', '~> 4.2'

end
